### ISSUE TITLE
Tara feature tracker

### ISSUE THREAD

**Issue by ksambhi** [Gum-Joe/tara#4]
Here is the feature tracker for tara

### v0.1.0 (MVP, minimum viable product)

**Major change:** moved to electron-webpack with #10 

- [x] Plugin API 📦 
  - [x] Layout
  - [x] Plugin bridge (allows plugins to communicate)
- [ ] Themes API :art:
  - Issues :bug::
    - [x] #1 
    - [x] #5 
  - [ ] Base themes 🎨:
    - [ ] One-fluent-design (#3)
- [ ] tara:// protocol API 🚀 (#2)
- [x] Explorer plugin 📁
    - [x] File listing 📜
      - [x] List dirs & files
      - [x] Show file icons for folders & file only
    - [ ] File operation handling
      - [ ] Copy
      - [ ] Paste
      - [ ] Cut/move
- [x] Address bar (plugin)
  - [x] Show dir
  - [x] Action buttons

### v0.2.0
- [ ] Performance 🚀 
  - [ ] Cache compiled theme
  - [ ] Cache directories
  - [ ] Use preact
  - [ ] Speed up webpack build
- [ ] Explorer:
  - [ ] Open files & handle default programs
  - [ ] File icons
- [ ] Virtual folders for libraries etc.

### v0.3.0
- [ ] Finder plugin 🔍
  - [ ] Standard folders 📁
    - [ ] Documents 📄 
    - [ ] Pictures 📷 
    - [ ] Videos 🎥 
    - [ ] Downloads ⬇️ 
    - [ ] Desktop 🖥 
    - [ ] Application List 💻 
  - [ ] Quick access/favourites ⭐️
  - [ ] Drives
  - [ ] Virtual folders
- [ ] Themes:
  - [ ] Dark theme
  - [ ] Light theme
